FROM evarga/jenkins-slave:latest

RUN  apt-get -y update && apt-get -y upgrade && \
     apt-get install -y software-properties-common python-software-properties

RUN  add-apt-repository --yes  ppa:beineri/opt-qt532-trusty &&\
     add-apt-repository ppa:ubuntu-toolchain-r/test && \
     add-apt-repository --yes ppa:openjdk-r/ppa && \
     apt-get -qq update && \
     apt-get install -y qt53base qt53websockets \
                firefox chromium-browser\
                xvfb \
                wkhtmltopdf \
                xsltproc \
                clang-format-3.6 \
                libxml2 libxml2-dev \
                lua-lpeg liblua5.2 liblua5.2-dev lua-lpeg-dev \
                cppcheck \
                libssl-dev libudev-dev libavahi-client-dev \
                sqlite3 \
                libsqlite3-dev \
                automake1.11 \
                libexpat1-dev \
                libpulse-dev \
                doxygen \
                graphviz \
                mscgen \
                libbluetooth3 libbluetooth-dev bluez-tools \
                libgl1-mesa-dev \
                libgtest-dev \
                binutils \
                cmake ccache cmake-curses-gui \
                gitk \
                g++-4.9 gcc-4.9 \
                dos2unix \
                gdebi \
                python-pip python-dev\
                curl
RUN wget http://archive.ubuntu.com/ubuntu/pool/main/l/lcov/lcov_1.11-3_all.deb && \
    dpkg -i lcov_1.11-3_all.deb
RUN ln -sf /usr/bin/gcov-4.9 /usr/bin/gcov && \
    pip install pylint

RUN locale-gen en_US.UTF-8
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US:en
ENV LC_ALL en_US.UTF-8

RUN echo -e '#!/bin/bash\nxvfb-run -a --server-args="-screen 0, 1024x768x24" /usr/bin/wkhtmltopdf -q $*' > /usr/bin/wkhtmltopdf.sh
RUN chmod a+x /usr/bin/wkhtmltopdf.sh && \
    chmod u+s /sbin/ifconfig && \
    ln -s /usr/bin/wkhtmltopdf.sh /usr/local/bin/wkhtmltopdf
